const {eras,types,events,people,regions}=window.ART_DATA;
const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
let activeType='all',activeEra='all',query='',visible=10;

const eraFilter=$('#eraFilter');eras.forEach(e=>{const o=document.createElement('option');o.value=e.id;o.textContent=`${e.years} · ${e.title}`;eraFilter.appendChild(o)});
const typeFilters=$('#typeFilters');['all',...types].forEach(t=>{const b=document.createElement('button');b.className='filter-chip'+(t==='all'?' active':'');b.dataset.type=t;b.textContent=t==='all'?'All':t;b.onclick=()=>{activeType=t;document.querySelectorAll('.filter-chip').forEach(x=>x.classList.toggle('active',x===b));visible=10;renderTimeline()};typeFilters.appendChild(b)});
eraFilter.onchange=()=>{activeEra=eraFilter.value;visible=10;renderTimeline()};
$('#searchInput').oninput=e=>{query=e.target.value.trim().toLowerCase();visible=10;renderTimeline()};
$('#focusSearch').onclick=()=>{location.hash='#timeline';setTimeout(()=>$('#searchInput').focus(),150)};

function filteredEvents(){return events.filter(e=>(activeType==='all'||e.type===activeType)&&(activeEra==='all'||e.era===activeEra)&&(!query||[e.title,e.place,e.type,e.summary,...e.people].join(' ').toLowerCase().includes(query)))}
function renderTimeline(){const list=$('#timelineList'),items=filteredEvents();list.innerHTML=items.slice(0,visible).map((e,i)=>`<article class="timeline-item"><div class="timeline-date">${esc(e.year)}</div><span class="timeline-dot"></span><div class="timeline-card" data-event="${i}" data-key="${esc(e.title)}"><div class="meta"><span>${esc(e.type)}</span><span>${esc(e.place)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="meta"><span>${e.people.slice(0,4).map(esc).join(' · ')}</span></div></div></article>`).join('')||`<div class="timeline-card"><h3>No matches found.</h3><p>Try another person, place, era or movement.</p></div>`;document.querySelectorAll('.timeline-card[data-event]').forEach(c=>c.onclick=()=>openEvent(c.dataset.key));$('#loadMore').style.display=items.length>visible?'block':'none'}

function renderPeople(){const grid=$('#peopleGrid');const featured=['Thomas Sankara','Kwame Nkrumah','Patrice Lumumba','Steve Biko','Nelson Mandela','Amílcar Cabral','Toussaint Louverture','Ibrahim Traoré'];grid.innerHTML=featured.map((name,i)=>{const p=people.find(x=>x.name===name);return `<article class="person-card" data-person="${esc(p.name)}"><span class="person-number">0${i+1}</span><div><h3>${esc(p.name)}</h3><p>${esc(p.country)}</p><div class="person-era">${esc(p.idea)} · ${esc(p.years)}</div></div></article>`}).join('');document.querySelectorAll('.person-card').forEach(c=>c.onclick=()=>openPerson(c.dataset.person))}
function renderEras(){const grid=$('#eraGrid');grid.innerHTML=eras.map(e=>`<article class="era-card"><strong>${e.number} / ${esc(e.years)}</strong><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><a class="text-link" href="#timeline" onclick="setEra('${e.id}')">Explore →</a></article>`).join('')}
function renderRegions(){const list=$('#regionList');list.innerHTML=regions.map(r=>`<div class="region"><div><strong>${esc(r.name)}</strong><br><small>${esc(r.count)}</small></div><span class="text-link">→</span></div>`).join('')}
window.setEra=id=>{activeEra=id;eraFilter.value=id;visible=10;renderTimeline();$('#timeline').scrollIntoView({behavior:'smooth'})};
function openEvent(title){const e=events.find(x=>x.title===title);if(!e)return;$('#dialogContent').innerHTML=`<div class="dialog-body"><span class="dialog-label">${esc(e.year)} · ${esc(e.type)}</span><h2>${esc(e.title)}</h2><p>${esc(e.summary)}</p><div class="dialog-columns"><div><strong>Place</strong><p>${esc(e.place)}</p></div><div><strong>People</strong><p>${e.people.map(esc).join('<br>')}</p></div></div></div>`;$('#detailDialog').showModal()}
function openPerson(name){const p=people.find(x=>x.name===name);if(!p)return;const related=events.filter(e=>e.people.includes(name)).slice(0,5);$('#dialogContent').innerHTML=`<div class="dialog-body"><span class="dialog-label">${esc(p.era)} · ${esc(p.years)}</span><h2>${esc(p.name)}</h2><p>${esc(p.bio)}</p><div class="dialog-columns"><div><strong>Country / region</strong><p>${esc(p.country)}</p><strong>Core idea</strong><p>${esc(p.idea)}</p></div><div><strong>Archive connections</strong><p>${related.map(e=>`${esc(e.year)} — ${esc(e.title)}`).join('<br>')||'More connections will be added as the archive grows.'}</p></div></div></div>`;$('#detailDialog').showModal()}
$('#dialogClose').onclick=()=>$('#detailDialog').close();$('#detailDialog').addEventListener('click',e=>{if(e.target===$('#detailDialog'))$('#detailDialog').close()});
renderTimeline();renderPeople();renderEras();renderRegions();
