const legacy=window.ART_DATA||{};
const kg=window.ART_KNOWLEDGE||{};
const p3=window.ART_PHASE3||{};
const p4=window.ART_PHASE4||{};
const p5=window.ART_PHASE5||{};
const sourceRegistry=window.ART_SOURCES||{};
const eras=legacy.eras||[]; const types=legacy.types||[]; const baseEvents=legacy.events||[]; const basePeople=legacy.people||[]; const regions=legacy.regions||[];
const graphPeople=kg.entities?.people||[]; const graphEvents=kg.entities?.events||[]; const movements=[...(kg.entities?.movements||[])]; const relations=kg.entities?.relations||[];
const allPeople=[...basePeople]; [...graphPeople,...(p3.people||[]),...(p4.people||[])].forEach(g=>{const name=g.name;if(!name||allPeople.some(p=>p.name===name))return;allPeople.push({name,country:g.country||g.place||g.region,years:g.active,era:g.era||'archive',idea:g.ideas?.[0]||'',bio:g.summary})});
const phaseEvents=[...(p3.events||[]),...(p4.events||[]),...(p5.events||[])]; const byTitle=new Set(); const events=[]; [...baseEvents,...graphEvents,...phaseEvents].forEach(e=>{if(!e?.title||byTitle.has(e.title))return;byTitle.add(e.title);events.push({...e})});
const phaseMovements=[...(p3.movements||[]),...(p4.movements||[])]; phaseMovements.forEach(m=>{if(m?.id&&!movements.some(x=>x.id===m.id))movements.push(m)});
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])); const slug=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
let activeType='all',activeEra='all',query='',visible=10,countryQuery='',colonial='all';
const eraFilter=$('#eraFilter'); if(eraFilter){eras.forEach(e=>{const o=document.createElement('option');o.value=e.id;o.textContent=`${e.years} · ${e.title}`;eraFilter.appendChild(o)})};
const typeFilters=$('#typeFilters'); if(typeFilters){['all',...types].forEach(t=>{const b=document.createElement('button');b.className='filter-chip'+(t==='all'?' active':'');b.dataset.type=t;b.textContent=t==='all'?'All':t;b.onclick=()=>{activeType=t;document.querySelectorAll('.filter-chip').forEach(x=>x.classList.toggle('active',x===b));visible=10;renderTimeline()};typeFilters.appendChild(b)})};
if(eraFilter)eraFilter.onchange=()=>{activeEra=eraFilter.value;visible=10;renderTimeline()}; if($('#searchInput'))$('#searchInput').oninput=e=>{query=e.target.value.trim().toLowerCase();visible=10;renderTimeline()}; if($('#focusSearch'))$('#focusSearch').onclick=()=>{location.hash='#timeline';setTimeout(()=>$('#searchInput')?.focus(),150)}; if($('#loadMore'))$('#loadMore').onclick=()=>{visible+=10;renderTimeline()};
function matchesQuery(e){return !query||[e.title,e.place,e.type,e.summary,...(e.people||[])].join(' ').toLowerCase().includes(query)}
function filteredEvents(){return events.filter(e=>(activeType==='all'||e.type===activeType)&&(activeEra==='all'||e.era===activeEra)&&matchesQuery(e))}
function personGraph(name){return graphPeople.find(p=>p.name===name)||graphPeople.find(p=>slug(p.name)===slug(name))||p3.people?.find(p=>p.name===name)||p4.people?.find(p=>p.name===name)}
function personByName(name){return allPeople.find(p=>p.name===name)||allPeople.find(p=>slug(p.name)===slug(name))}
function relationFor(name){const id=personGraph(name)?.id;if(!id)return[];return [...relations,...(p4.relations||[]),...(p3.relations||[])].filter(r=>r.from===id||r.to===id)}
function movementFor(name){const id=personGraph(name)?.id;if(!id)return[];return movements.filter(m=>(m.people||[]).includes(id))}
function renderTimeline(){const list=$('#timelineList');if(!list)return;const items=filteredEvents();list.innerHTML=items.slice(0,visible).map(e=>`<article class="timeline-item"><div class="timeline-date">${esc(e.year)}</div><span class="timeline-dot"></span><div class="timeline-card" data-key="${esc(e.title)}"><div class="meta"><span>${esc(e.type||'Archive')}</span><span>${esc(e.place)}</span></div><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><div class="meta"><span>${(e.people||[]).slice(0,4).map(x=>esc(personByName(x)?.name||graphPeople.find(p=>p.id===x)?.name||p3.people?.find(p=>p.id===x)?.name||p4.people?.find(p=>p.id===x)?.name||x)).join(' · ')}</span></div></div></article>`).join('')||`<div class="timeline-card"><h3>No matches found.</h3><p>Try another person, place, event or era.</p></div>`;document.querySelectorAll('.timeline-card[data-key]').forEach(c=>c.onclick=()=>openEvent(c.dataset.key));if($('#loadMore'))$('#loadMore').style.display=items.length>visible?'block':'none'}
function renderPeople(){const grid=$('#peopleGrid');if(!grid)return;const featured=['Rei Amador','Yaa Asantewaa','Marcus Garvey','W. E. B. Du Bois','Kwame Nkrumah','Ruben Um Nyobè','Frantz Fanon','Thomas Sankara'];grid.innerHTML=featured.map((name,i)=>{const p=personByName(name)||{};return `<article class="person-card" data-person="${esc(p.name||name)}"><span class="person-number">${String(i+1).padStart(2,'0')}</span><div><h3>${esc(p.name||name)}</h3><p>${esc(p.country)}</p><div class="person-era">${esc(p.idea)} · ${esc(p.years)}</div></div></article>`}).join('');document.querySelectorAll('.person-card').forEach(c=>c.onclick=()=>openPerson(c.dataset.person))}
function renderEras(){const grid=$('#eraGrid');if(!grid)return;grid.innerHTML=eras.map(e=>`<article class="era-card"><strong>${e.number} / ${esc(e.years)}</strong><h3>${esc(e.title)}</h3><p>${esc(e.summary)}</p><a class="text-link" href="#timeline" onclick="setEra('${e.id}')">Explore →</a></article>`).join('')}
function renderRegions(){const list=$('#regionList');if(!list)return;list.innerHTML=regions.map(r=>`<div class="region"><div><strong>${esc(r.name)}</strong><br><small>${esc(r.count)}</small></div><span class="text-link">→</span></div>`).join('')}
function renderCountries(){const table=$('#countryTable');if(!table||!p5.countries)return;const filter=$('#colonialFilter');if(filter&&!filter.dataset.ready){[...new Set(p5.countries.map(c=>c.formerColonial))].sort().forEach(value=>{const o=document.createElement('option');o.value=value;o.textContent=value;filter.appendChild(o)});filter.dataset.ready='1';filter.onchange=e=>{colonial=e.target.value;renderCountries()}}const items=p5.countries.filter(c=>(colonial==='all'||c.formerColonial===colonial)&&(!countryQuery||[c.name,c.formerColonial,c.leader,c.movement,c.note].join(' ').toLowerCase().includes(countryQuery)));table.innerHTML=items.map(c=>`<tr><td><strong>${esc(c.name)}</strong><button class="table-link" data-country="${esc(c.name)}" aria-label="Open ${esc(c.name)} archive">Explore</button></td><td>${esc(c.formerColonial)}</td><td><span class="year-pill">${esc(c.independence)}</span></td><td>${esc(c.leader)}</td><td>${esc(c.movement)}</td></tr>`).join('')||`<tr><td colspan="5"><div class="empty-state">No countries match the current filters.</div></td></tr>`;document.querySelectorAll('.table-link').forEach(b=>b.onclick=()=>openCountry(b.dataset.country))}
function openCountry(name){const c=p5.countries?.find(x=>x.name===name);if(!c||!$('#dialogContent'))return;$('#dialogContent').innerHTML=`<div class="dialog-body"><span class="dialog-label">${esc(c.year)} · Independence</span><h2>${esc(c.name)}</h2><p>${esc(c.note)}</p><div class="dialog-columns"><div><strong>Former colonial power / status</strong><p>${esc(c.formerColonial)}</p><strong>Independence</strong><p>${esc(c.independence)}</p></div><div><strong>Political generation</strong><p>${esc(c.leader)}</p><strong>Movement / context</strong><p>${esc(c.movement)}</p></div></div><div class="archive-note"><strong>Archive note</strong><p>Independence is treated as one event within a longer country history. Later liberation wars, political ruptures and sovereignty struggles remain connected on the main timeline.</p></div></div>`;$('#detailDialog')?.showModal()}
window.setEra=id=>{activeEra=id;if(eraFilter)eraFilter.value=id;visible=10;renderTimeline();$('#timeline')?.scrollIntoView({behavior:'smooth'})};
function openEvent(title){const e=events.find(x=>x.title===title);if(!e||!$('#dialogContent'))return;const names=(e.people||[]).map(id=>personByName(id)?.name||graphPeople.find(p=>p.id===id)?.name||p3.people?.find(p=>p.id===id)?.name||p4.people?.find(p=>p.id===id)?.name||id);const movement=movements.find(m=>m.id===e.movement);$('#dialogContent').innerHTML=`<div class="dialog-body"><span class="dialog-label">${esc(e.year)} · ${esc(e.type||'Archive')}</span><h2>${esc(e.title)}</h2><p>${esc(e.summary)}</p><div class="dialog-columns"><div><strong>Place</strong><p>${esc(e.place)}</p>${movement?`<strong>Movement</strong><p>${esc(movement.name)}</p>`:''}</div><div><strong>People</strong><p>${names.map(esc).join('<br>')||'Archive connections will be expanded as sourcing continues.'}</p></div></div><div class="archive-note"><strong>Archive status</strong><p>Chronology, interpretation and attribution should be read alongside the source record as the archive is expanded.</p></div></div>`;$('#detailDialog')?.showModal()}
function openPerson(name){const p=personByName(name)||personGraph(name);if(!p||!$('#dialogContent'))return;const gp=personGraph(p.name),personId=gp?.id;const relatedEvents=events.filter(e=>(e.people||[]).some(x=>x===p.name||x===personId)).slice(0,10);const rel=relationFor(p.name);const mov=movementFor(p.name);const ideas=gp?.ideas||[p.idea].filter(Boolean);const connections=rel.map(r=>{const otherId=r.from===personId?r.to:r.from;const other=graphPeople.find(x=>x.id===otherId)||p3.people?.find(x=>x.id===otherId)||p4.people?.find(x=>x.id===otherId);return other?`${r.type} · ${other.name}`:null}).filter(Boolean);$('#dialogContent').innerHTML=`<div class="dialog-body"><span class="dialog-label">${esc(p.era)} · ${esc(p.years||p.active||'')}</span><h2>${esc(p.name)}</h2><p>${esc(p.bio||p.summary||'')}</p><div class="dialog-columns"><div><strong>Country / region</strong><p>${esc(p.country||p.place||p.region)}</p><strong>Core ideas</strong><p>${ideas.map(esc).join(' · ')||'To be expanded'}</p>${mov.length?`<strong>Movements</strong><p>${mov.map(m=>esc(m.name)).join('<br>')}</p>`:''}</div><div><strong>Archive connections</strong><p>${connections.join('<br>')||'More relationships will be added as the archive grows.'}</p><strong>Timeline</strong><p>${relatedEvents.map(e=>`${esc(e.year)} — ${esc(e.title)}`).join('<br>')||'Related events will be expanded.'}</p></div></div><div class="archive-note"><strong>Source discipline</strong><p>${esc(sourceRegistry.policy?.rule||'Claims should be traceable to reliable historical evidence.')}</p></div></div>`;$('#detailDialog')?.showModal()}
if($('#dialogClose'))$('#dialogClose').onclick=()=>$('#detailDialog').close();$('#detailDialog')?.addEventListener('click',e=>{if(e.target===$('#detailDialog'))$('#detailDialog').close()});
if($('#countrySearch'))$('#countrySearch').oninput=e=>{countryQuery=e.target.value.trim().toLowerCase();renderCountries()}; renderTimeline();renderPeople();renderEras();renderRegions();renderCountries();
