window.ART_DATA={
 eras:[
  {id:'resistance',number:'I',title:'Resistance to Enslavement',years:'1500–1790',summary:'African resistance to enslavement, slave-raiding and plantation systems.'},
  {id:'black-revolution',number:'II',title:'Black Revolution',years:'1791–1900',summary:'Haiti, abolition, Black sovereignty and the Atlantic revolutionary world.'},
  {id:'empire',number:'III',title:'Resistance to Empire',years:'1800–1945',summary:'Armed and political resistance to European conquest and colonial rule.'},
  {id:'pan-african',number:'IV',title:'Pan-African Revolution',years:'1900–1960',summary:'Pan-Africanism, Black internationalism and the intellectual struggle for liberation.'},
  {id:'independence',number:'V',title:'Independence',years:'1950–1975',summary:'The great wave of African national liberation and political independence.'},
  {id:'liberation',number:'VI',title:'Liberation',years:'1960–1994',summary:'Southern African liberation, Black Consciousness and the defeat of apartheid.'},
  {id:'sovereignty',number:'VII',title:'Sovereignty',years:'1994–2026',summary:'Economic sovereignty, popular uprisings and contemporary African self-determination.'}
 ],
 types:['Resistance','Revolution','Anti-colonial','Independence','Pan-African','Liberation','Sovereignty'],
 events:[
  {year:'1595',title:'Rei Amador Revolt',place:'São Tomé',type:'Resistance',era:'resistance',summary:'A major African-led uprising against Portuguese plantation slavery on São Tomé.',people:['Rei Amador']},
  {year:'1684',title:'Lourenço da Silva Mendonça',place:'Kongo / Angola → Rome',type:'Resistance',era:'resistance',summary:'An African royal figure takes an early legal and theological case against the enslavement of Africans to Rome.',people:['Lourenço da Silva Mendonça']},
  {year:'1791',title:'Haitian Revolution begins',place:'Saint-Domingue / Haiti',type:'Revolution',era:'black-revolution',summary:'Enslaved Africans launch the revolution that ultimately destroys the plantation-slavery regime and creates an independent Black republic.',people:['Dutty Boukman','Cécile Fatiman','Toussaint Louverture','Jean-Jacques Dessalines']},
  {year:'1804',title:'Haiti declares independence',place:'Haiti',type:'Independence',era:'black-revolution',summary:'Jean-Jacques Dessalines declares Haitian independence, creating the first modern state born from a successful slave revolution.',people:['Jean-Jacques Dessalines','Henri Christophe','Alexandre Pétion']},
  {year:'1850s–1900s',title:'African resistance to colonial conquest',place:'West, East & Southern Africa',type:'Anti-colonial',era:'empire',summary:'Across the continent, African states and communities wage military and political resistance against European imperial expansion.',people:['Samori Touré','Yaa Asantewaa','Mkwawa','Hendrik Witbooi','Nehanda Charwe Nyakasikana']},
  {year:'1905–1907',title:'Maji Maji Uprising',place:'Tanganyika',type:'Anti-colonial',era:'empire',summary:'A major uprising against German colonial rule, forced labour, taxation and cotton production.',people:['Kinjeketile Ngwale']},
  {year:'1919',title:'Pan-African Congress',place:'Paris',type:'Pan-African',era:'pan-african',summary:'Black internationalists organise around self-determination, anti-colonialism and racial justice.',people:['W. E. B. Du Bois','Marcus Garvey']},
  {year:'1945',title:'Fifth Pan-African Congress',place:'Manchester, United Kingdom',type:'Pan-African',era:'pan-african',summary:'A pivotal gathering of anti-colonial activists that helps shape the post-war independence generation.',people:['W. E. B. Du Bois','George Padmore','Kwame Nkrumah','Jomo Kenyatta']},
  {year:'1952–1960',title:'Mau Mau uprising',place:'Kenya',type:'Anti-colonial',era:'independence',summary:'Armed and political resistance to British colonial rule, land dispossession and racial hierarchy.',people:['Dedan Kimathi','Muthoni wa Kirima','Jomo Kenyatta']},
  {year:'1954–1962',title:'Algerian Revolution',place:'Algeria',type:'Revolution',era:'independence',summary:'The FLN-led struggle defeats French colonial rule after eight years of war and mass mobilisation.',people:['Ahmed Ben Bella','Larbi Ben M’hidi','Djamila Bouhired','Frantz Fanon']},
  {year:'1957',title:'Ghana independence',place:'Ghana',type:'Independence',era:'independence',summary:'Ghana becomes independent under Kwame Nkrumah and becomes a major centre of Pan-African politics.',people:['Kwame Nkrumah']},
  {year:'1960–1961',title:'Congo Crisis & Lumumba',place:'DR Congo',type:'Independence',era:'independence',summary:'Congo independence is followed by secession, foreign intervention and the assassination of Prime Minister Patrice Lumumba.',people:['Patrice Lumumba','Pierre Mulele']},
  {year:'1963',title:'Organisation of African Unity',place:'Addis Ababa, Ethiopia',type:'Pan-African',era:'independence',summary:'Independent African states establish a continental organisation dedicated to unity and cooperation.',people:['Kwame Nkrumah','Haile Selassie','Julius Nyerere']},
  {year:'1964–1975',title:'Portuguese colonial liberation wars',place:'Angola, Mozambique, Guinea-Bissau',type:'Liberation',era:'liberation',summary:'National liberation movements fight Portuguese colonial rule until the Portuguese Revolution triggers decolonisation.',people:['Amílcar Cabral','Eduardo Mondlane','Samora Machel','Agostinho Neto']},
  {year:'1976',title:'Soweto uprising',place:'South Africa',type:'Liberation',era:'liberation',summary:'Students rise against apartheid education policy, becoming a defining moment in the anti-apartheid struggle.',people:['Steve Biko','Hector Pieterson']},
  {year:'1983',title:'Burkinabè Revolution',place:'Burkina Faso',type:'Revolution',era:'liberation',summary:'Thomas Sankara leads a revolutionary government centred on self-reliance, social transformation and anti-imperialism.',people:['Thomas Sankara']},
  {year:'1987',title:'Assassination of Thomas Sankara',place:'Ouagadougou, Burkina Faso',type:'Liberation',era:'liberation',summary:'Sankara is assassinated; his political legacy becomes a lasting reference point for African sovereignty and self-reliance.',people:['Thomas Sankara','Blaise Compaoré']},
  {year:'1990–1994',title:'End of apartheid',place:'South Africa',type:'Liberation',era:'liberation',summary:'Negotiations and mass political struggle culminate in South Africa’s first democratic elections in 1994.',people:['Nelson Mandela','Oliver Tambo','Walter Sisulu','Chris Hani','Winnie Madikizela-Mandela']},
  {year:'2011',title:'African popular uprisings',place:'North Africa',type:'Revolution',era:'sovereignty',summary:'Mass uprisings in Tunisia and Egypt reshape political life across North Africa and influence protest movements globally.',people:['Alaa Salah']},
  {year:'2019',title:'Sudanese Revolution',place:'Sudan',type:'Revolution',era:'sovereignty',summary:'A mass civilian movement helps remove Omar al-Bashir after months of protests and strikes.',people:['Alaa Salah']},
  {year:'2020',title:'Mali political rupture',place:'Mali',type:'Sovereignty',era:'sovereignty',summary:'A military coup removes President Ibrahim Boubacar Keïta amid political crisis and public discontent.',people:['Assimi Goïta']},
  {year:'2022',title:'Burkina Faso political rupture',place:'Burkina Faso',type:'Sovereignty',era:'sovereignty',summary:'A second coup in 2022 brings Captain Ibrahim Traoré to power amid insecurity and growing demands for sovereignty.',people:['Ibrahim Traoré']},
  {year:'2023',title:'Niger political rupture',place:'Niger',type:'Sovereignty',era:'sovereignty',summary:'A military takeover in Niger is followed by a major confrontation with the regional political order.',people:['Abdourahamane Tiani']},
  {year:'2023',title:'Alliance of Sahel States formed',place:'Burkina Faso · Mali · Niger',type:'Sovereignty',era:'sovereignty',summary:'Burkina Faso, Mali and Niger establish the AES, presenting the alliance around collective defence and sovereignty.',people:['Ibrahim Traoré','Assimi Goïta','Abdourahamane Tiani']},
  {year:'2024',title:'AES Confederation',place:'Niamey, Niger',type:'Sovereignty',era:'sovereignty',summary:'The three Sahel states formalise their alliance as a confederation and deepen cooperation in defence, diplomacy and development.',people:['Ibrahim Traoré','Assimi Goïta','Abdourahamane Tiani']},
  {year:'2025',title:'AES states leave ECOWAS',place:'West Africa',type:'Sovereignty',era:'sovereignty',summary:'Burkina Faso, Mali and Niger formally leave ECOWAS, marking a major rupture in the regional order.',people:['Ibrahim Traoré','Assimi Goïta','Abdourahamane Tiani']},
  {year:'2026',title:'AES Unified Force framework',place:'Sahel',type:'Sovereignty',era:'sovereignty',summary:'The AES moves toward deeper unified military structures as the confederation enters a new phase of institutional consolidation.',people:['Ibrahim Traoré','Assimi Goïta','Abdourahamane Tiani']}
 ],
 people:[
  {name:'Rei Amador',country:'São Tomé',years:'16th century',era:'Resistance',idea:'Liberation',bio:'Leader associated with the 1595–1596 Angolar revolt against Portuguese plantation slavery.'},
  {name:'Toussaint Louverture',country:'Haiti',years:'c.1743–1803',era:'Black Revolution',idea:'Freedom',bio:'Major leader of the Haitian Revolution whose political and military leadership transformed the struggle against slavery.'},
  {name:'Yaa Asantewaa',country:'Ghana',years:'c.1840–1921',era:'Anti-colonial',idea:'Resistance',bio:'Queen mother of Ejisu who led the 1900 War of the Golden Stool against British colonial rule.'},
  {name:'Samori Touré',country:'West Africa',years:'c.1830–1900',era:'Anti-colonial',idea:'Sovereignty',bio:'Founder of the Wassoulou Empire and one of the major military opponents of French expansion in West Africa.'},
  {name:'Marcus Garvey',country:'Jamaica / Diaspora',years:'1887–1940',era:'Pan-African',idea:'Unity',bio:'Global Black organiser whose UNIA built a mass movement around African dignity, self-determination and Black internationalism.'},
  {name:'W. E. B. Du Bois',country:'United States / Diaspora',years:'1868–1963',era:'Pan-African',idea:'Pan-Africanism',bio:'Scholar and organiser central to the Pan-African Congress tradition and the international struggle against colonialism and racism.'},
  {name:'Kwame Nkrumah',country:'Ghana',years:'1909–1972',era:'Independence',idea:'Unity',bio:'Ghana’s first prime minister and president; a central advocate of continental African political unity.'},
  {name:'Patrice Lumumba',country:'DR Congo',years:'1925–1961',era:'Independence',idea:'Sovereignty',bio:'Congo’s first democratically elected prime minister and a symbol of uncompromising national sovereignty.'},
  {name:'Julius Nyerere',country:'Tanzania',years:'1922–1999',era:'Independence',idea:'Ujamaa',bio:'Founding president of Tanzania and influential Pan-African advocate of Ujamaa and continental unity.'},
  {name:'Gamal Abdel Nasser',country:'Egypt',years:'1918–1970',era:'Independence',idea:'Anti-imperialism',bio:'Egyptian president associated with Arab nationalism, the nationalisation of the Suez Canal and non-alignment.'},
  {name:'Amílcar Cabral',country:'Guinea-Bissau / Cape Verde',years:'1924–1973',era:'Liberation',idea:'National liberation',bio:'Founder and strategist of the PAIGC, renowned for linking armed liberation with political education and cultural identity.'},
  {name:'Frantz Fanon',country:'Martinique / Algeria',years:'1925–1961',era:'Decolonisation',idea:'Psychological liberation',bio:'Psychiatrist and revolutionary intellectual whose work became foundational to decolonisation theory.'},
  {name:'Nelson Mandela',country:'South Africa',years:'1918–2013',era:'Liberation',idea:'Dignity',bio:'Anti-apartheid leader, political prisoner and first president of democratic South Africa.'},
  {name:'Oliver Tambo',country:'South Africa',years:'1917–1993',era:'Liberation',idea:'Organisation',bio:'ANC leader who built international support for the anti-apartheid struggle during years in exile.'},
  {name:'Steve Biko',country:'South Africa',years:'1946–1977',era:'Liberation',idea:'Black Consciousness',bio:'Founder of a major Black Consciousness current that centred psychological liberation and Black self-definition.'},
  {name:'Samora Machel',country:'Mozambique',years:'1933–1986',era:'Liberation',idea:'Independence',bio:'First president of independent Mozambique and leader of FRELIMO during the liberation struggle.'},
  {name:'Thomas Sankara',country:'Burkina Faso',years:'1949–1987',era:'Revolution',idea:'Self-reliance',bio:'Revolutionary leader whose 1983–1987 government emphasised sovereignty, social transformation and anti-imperialism.'},
  {name:'Winnie Madikizela-Mandela',country:'South Africa',years:'1936–2018',era:'Liberation',idea:'Resistance',bio:'Anti-apartheid organiser whose activism became a prominent symbol of resistance during Mandela’s imprisonment.'},
  {name:'Ibrahim Traoré',country:'Burkina Faso',years:'b.1988',era:'Sovereignty',idea:'Self-determination',bio:'Burkinabè military leader associated with the contemporary sovereignty politics of the AES era.'},
  {name:'Assimi Goïta',country:'Mali',years:'b.1983',era:'Sovereignty',idea:'Strategic autonomy',bio:'Malian military leader and transitional president associated with Mali’s contemporary sovereignty agenda and the AES.'},
  {name:'Abdourahamane Tiani',country:'Niger',years:'b.1964',era:'Sovereignty',idea:'National sovereignty',bio:'Nigerien military leader associated with the 2023 political rupture and the AES.'}
 ],
 regions:[
  {name:'West Africa',count:'Resistance · independence · AES',focus:'Samori Touré · Yaa Asantewaa · Nkrumah · Sankara · AES'},
  {name:'North Africa',count:'Anti-colonial · non-alignment',focus:'Nasser · Fanon · Ben Bella · Algerian Revolution'},
  {name:'Central Africa',count:'Sovereignty · liberation',focus:'Lumumba · Mulele · Congo Crisis'},
  {name:'East Africa',count:'Anti-colonial · Pan-African',focus:'Mau Mau · Nyerere · Maji Maji'},
  {name:'Southern Africa',count:'Liberation · Black Consciousness',focus:'Biko · Mandela · Tambo · Machel · Nkomo · Nujoma'},
  {name:'Diaspora',count:'Black internationalism',focus:'Haiti · Garvey · Du Bois · Black Power'}
 ]
};
