window.ART_KNOWLEDGE={
 schemaVersion:1,
 entities:{
  people:[
   {id:'thomas-sankara',name:'Thomas Sankara',country:'Burkina Faso',birth:'1949',death:'1987',active:'1983–1987',era:'revolution',roles:['revolutionary','statesman'],ideas:['self-reliance','anti-imperialism','social transformation'],summary:'Revolutionary leader of Burkina Faso whose government pursued sovereignty, social transformation, public mobilisation and self-reliance.'},
   {id:'kwame-nkrumah',name:'Kwame Nkrumah',country:'Ghana',birth:'1909',death:'1972',active:'1947–1966',era:'independence',roles:['political leader','Pan-Africanist'],ideas:['Pan-Africanism','unity','independence'],summary:'Ghanaian independence leader and major advocate of continental African political unity.'},
   {id:'patrice-lumumba',name:'Patrice Lumumba',country:'DR Congo',birth:'1925',death:'1961',active:'1958–1961',era:'independence',roles:['political leader','nationalist'],ideas:['sovereignty','national unity','anti-colonialism'],summary:'Congo’s first democratically elected prime minister and a lasting symbol of national sovereignty.'},
   {id:'julius-nyerere',name:'Julius Nyerere',country:'Tanzania',birth:'1922',death:'1999',active:'1954–1985',era:'independence',roles:['political leader','Pan-Africanist'],ideas:['Ujamaa','unity','African socialism'],summary:'Founding president of Tanzania and a leading advocate of African unity and Ujamaa.'},
   {id:'frantz-fanon',name:'Frantz Fanon',country:'Martinique / Algeria',birth:'1925',death:'1961',active:'1940s–1961',era:'decolonisation',roles:['revolutionary intellectual','psychiatrist'],ideas:['decolonisation','psychological liberation','national consciousness'],summary:'Revolutionary intellectual whose writing became foundational to modern decolonisation thought.'},
   {id:'amilcar-cabral',name:'Amílcar Cabral',country:'Guinea-Bissau / Cape Verde',birth:'1924',death:'1973',active:'1950s–1973',era:'liberation',roles:['revolutionary','organiser','political theorist'],ideas:['national liberation','political education','cultural identity'],summary:'Founder and strategist of the PAIGC, linking national liberation to political education and culture.'},
   {id:'steve-biko',name:'Steve Biko',country:'South Africa',birth:'1946',death:'1977',active:'1968–1977',era:'liberation',roles:['activist','Black Consciousness leader'],ideas:['Black Consciousness','psychological liberation','self-definition'],summary:'Central figure in South African Black Consciousness, emphasising psychological liberation and Black self-definition.'},
   {id:'nelson-mandela',name:'Nelson Mandela',country:'South Africa',birth:'1918',death:'2013',active:'1944–1994',era:'liberation',roles:['revolutionary','political leader'],ideas:['liberation','dignity','reconciliation'],summary:'Anti-apartheid leader, political prisoner and first president of democratic South Africa.'},
   {id:'yaa-asantewaa',name:'Yaa Asantewaa',country:'Asante / Ghana',birth:'c.1840',death:'1921',active:'1900',era:'empire',roles:['war leader','queen mother'],ideas:['resistance','sovereignty'],summary:'Queen mother of Ejisu who led the 1900 resistance to British colonial rule.'},
   {id:'samori-toure',name:'Samori Touré',country:'West Africa',birth:'c.1830',death:'1900',active:'1870s–1898',era:'empire',roles:['military leader','state builder'],ideas:['sovereignty','resistance'],summary:'Founder of the Wassoulou Empire and major military opponent of French expansion in West Africa.'},
   {id:'toussaint-louverture',name:'Toussaint Louverture',country:'Haiti',birth:'c.1743',death:'1803',active:'1791–1802',era:'black-revolution',roles:['revolutionary','military leader'],ideas:['freedom','emancipation','sovereignty'],summary:'Major leader of the Haitian Revolution and one of the most influential figures in the destruction of French colonial slavery in Saint-Domingue.'},
   {id:'jean-jacques-dessalines',name:'Jean-Jacques Dessalines',country:'Haiti',birth:'c.1758',death:'1806',active:'1791–1806',era:'black-revolution',roles:['revolutionary','military leader'],ideas:['independence','Black sovereignty'],summary:'Revolutionary commander who declared Haitian independence in 1804.'},
   {id:'rei-amador',name:'Rei Amador',country:'São Tomé',birth:null,death:null,active:'1595–1596',era:'resistance',roles:['rebel leader'],ideas:['liberation','resistance'],summary:'Leader associated with the Angolar revolt against Portuguese plantation slavery on São Tomé.'},
   {id:'ibrahim-traore',name:'Ibrahim Traoré',country:'Burkina Faso',birth:'1988',death:null,active:'2022–present',era:'sovereignty',roles:['military leader','head of state'],ideas:['sovereignty','self-determination','strategic autonomy'],summary:'Burkinabè military leader associated with the contemporary sovereignty politics of the Sahel and AES.'}
  ],
  events:[
   {id:'rei-amador-revolt',year:'1595–1596',title:'Rei Amador Revolt',place:'São Tomé',type:'Resistance',era:'resistance',summary:'African-led uprising against Portuguese plantation slavery.',people:['rei-amador']},
   {id:'haitian-revolution',year:'1791–1804',title:'Haitian Revolution',place:'Saint-Domingue / Haiti',type:'Revolution',era:'black-revolution',summary:'Successful revolution against slavery and French colonial rule that produced an independent Black republic.',people:['toussaint-louverture','jean-jacques-dessalines']},
   {id:'maji-maji',year:'1905–1907',title:'Maji Maji Uprising',place:'Tanganyika',type:'Anti-colonial',era:'empire',summary:'Large-scale resistance to German colonial taxation, forced labour and cotton production.',people:[]},
   {id:'fifth-pac',year:'1945',title:'Fifth Pan-African Congress',place:'Manchester, United Kingdom',type:'Pan-African',era:'pan-african',summary:'Major post-war Pan-African gathering that helped shape the independence generation.',people:['w-e-b-du-bois','kwame-nkrumah']},
   {id:'ghana-independence',year:'1957',title:'Ghana Independence',place:'Ghana',type:'Independence',era:'independence',summary:'Ghana becomes independent and becomes a major centre of Pan-African political activity.',people:['kwame-nkrumah']},
   {id:'algerian-revolution',year:'1954–1962',title:'Algerian Revolution',place:'Algeria',type:'Revolution',era:'independence',summary:'FLN-led struggle that ends French colonial rule after eight years of war and mobilisation.',people:['frantz-fanon']},
   {id:'congo-crisis',year:'1960–1965',title:'Congo Crisis',place:'DR Congo',type:'Independence',era:'independence',summary:'Independence is followed by secession, foreign intervention and prolonged political conflict.',people:['patrice-lumumba']},
   {id:'soweto',year:'1976',title:'Soweto Uprising',place:'South Africa',type:'Liberation',era:'liberation',summary:'Student uprising against apartheid education policy that becomes a defining anti-apartheid event.',people:['steve-biko']},
   {id:'burkinabe-revolution',year:'1983–1987',title:'Burkinabè Revolution',place:'Burkina Faso',type:'Revolution',era:'liberation',summary:'Thomas Sankara leads a revolutionary government focused on sovereignty, self-reliance and social transformation.',people:['thomas-sankara']},
   {id:'south-african-democracy',year:'1994',title:'South African Democratic Transition',place:'South Africa',type:'Liberation',era:'liberation',summary:'South Africa holds its first democratic national elections after decades of apartheid rule.',people:['nelson-mandela']},
   {id:'mali-rupture',year:'2020',title:'Mali Political Rupture',place:'Mali',type:'Sovereignty',era:'sovereignty',summary:'A military takeover removes President Ibrahim Boubacar Keïta amid political crisis.',people:[]},
   {id:'burkina-rupture',year:'2022',title:'Burkina Faso Political Rupture',place:'Burkina Faso',type:'Sovereignty',era:'sovereignty',summary:'Captain Ibrahim Traoré takes power amid insecurity and a growing sovereignty-oriented political discourse.',people:['ibrahim-traore']},
   {id:'niger-rupture',year:'2023',title:'Niger Political Rupture',place:'Niger',type:'Sovereignty',era:'sovereignty',summary:'Military takeover followed by confrontation with the established regional order.',people:[]},
   {id:'aes-formed',year:'2023',title:'Alliance of Sahel States Formed',place:'Burkina Faso · Mali · Niger',type:'Sovereignty',era:'sovereignty',summary:'Burkina Faso, Mali and Niger establish the AES around collective defence and sovereignty.',people:['ibrahim-traore']},
   {id:'aes-confederation',year:'2024',title:'AES Confederation',place:'Niamey, Niger',type:'Sovereignty',era:'sovereignty',summary:'The three Sahel states formalise the alliance as a confederation and deepen cooperation.',people:['ibrahim-traore']},
   {id:'ecowas-exit',year:'2025',title:'AES States Leave ECOWAS',place:'West Africa',type:'Sovereignty',era:'sovereignty',summary:'Burkina Faso, Mali and Niger formally leave ECOWAS.',people:['ibrahim-traore']}
  ],
  movements:[
   {id:'haitian-revolution',name:'Haitian Revolution',period:'1791–1804',region:'Caribbean / Atlantic',ideas:['emancipation','Black sovereignty'],people:['toussaint-louverture','jean-jacques-dessalines'],events:['haitian-revolution']},
   {id:'pan-africanism',name:'Pan-Africanism',period:'1900s–present',region:'Africa & Diaspora',ideas:['unity','self-determination','anti-colonialism'],people:['kwame-nkrumah','frantz-fanon'] ,events:['fifth-pac']},
   {id:'algerian-liberation',name:'Algerian Liberation',period:'1954–1962',region:'North Africa',ideas:['decolonisation','national liberation'],people:['frantz-fanon'],events:['algerian-revolution']},
   {id:'black-consciousness',name:'Black Consciousness',period:'1960s–1970s',region:'Southern Africa',ideas:['psychological liberation','self-definition'],people:['steve-biko'],events:['soweto']},
   {id:'burkinabe-revolution',name:'Burkinabè Revolution',period:'1983–1987',region:'West Africa',ideas:['self-reliance','social transformation','anti-imperialism'],people:['thomas-sankara'],events:['burkinabe-revolution']},
   {id:'aes',name:'Alliance of Sahel States',period:'2023–present',region:'West Africa / Sahel',ideas:['sovereignty','regional integration','strategic autonomy'],people:['ibrahim-traore'],events:['aes-formed','aes-confederation','ecowas-exit']}
  ],
  relations:[
   {from:'frantz-fanon',to:'steve-biko',type:'influenced',note:'Fanon’s work became an important intellectual reference point for Black Consciousness.'},
   {from:'kwame-nkrumah',to:'thomas-sankara',type:'legacy',note:'Nkrumah’s Pan-African and anti-imperialist legacy is part of the broader lineage invoked by later African revolutionaries.'},
   {from:'thomas-sankara',to:'ibrahim-traore',type:'legacy',note:'Sankara is frequently invoked in contemporary Burkinabè political symbolism; the governments should still be studied on their own terms.'},
   {from:'kwame-nkrumah',to:'patrice-lumumba',type:'contemporary',note:'Both were central figures in the independence era and Pan-African political imagination.'}
  ]
 },
 sources:{policy:'All historical claims should eventually be attached to one or more primary or reputable secondary sources. Record source type, title, author, publication date, URL or archive reference, and claim scope.'}
};
