window.ART_PHASE4={
 schemaVersion:1,
 period:{start:1900,end:1960,coverage:'Pan-Africanism, Black internationalism and the independence generation'},
 people:[
  {id:'w-e-b-du-bois',name:'W. E. B. Du Bois',region:'African diaspora',place:'United States / Ghana',active:'1900–1963',role:'scholar and organiser',ideas:['Pan-Africanism','self-determination','anti-racism'],summary:'Scholar and organiser central to the Pan-African Congress tradition and international anti-colonial politics.'},
  {id:'marcus-garvey',name:'Marcus Garvey',region:'African diaspora',place:'Jamaica / United States',active:'1914–1940',role:'organiser',ideas:['Black nationalism','self-determination','African unity'],summary:'Founder of the UNIA and one of the most influential Black international organisers of the early twentieth century.'},
  {id:'amy-ashwood-garvey',name:'Amy Ashwood Garvey',region:'African diaspora',place:'Jamaica / United States / Africa',active:'1914–1960s',role:'organiser',ideas:['Pan-Africanism','women’s leadership','Black self-determination'],summary:'Pan-African organiser and co-founder of the UNIA whose political work helped build transnational Black organising.'},
  {id:'amy-jacques-garvey',name:'Amy Jacques Garvey',region:'African diaspora',place:'Jamaica / United States',active:'1920s–1970s',role:'writer and organiser',ideas:['Black self-determination','African unity'],summary:'Writer, editor and organiser who preserved and extended Marcus Garvey’s political legacy.'},
  {id:'george-padmore',name:'George Padmore',region:'Caribbean / Africa',place:'Trinidad / United Kingdom / Ghana',active:'1920s–1959',role:'organiser and journalist',ideas:['anti-colonialism','Pan-Africanism','internationalism'],summary:'Trinidadian organiser and journalist who became a major bridge between Black internationalism, anti-colonial movements and African independence leaders.'},
  {id:'cl-r-james',name:'C. L. R. James',region:'Caribbean / diaspora',place:'Trinidad / United Kingdom',active:'1930s–1989',role:'writer and organiser',ideas:['revolution','anti-colonialism','Black internationalism'],summary:'Trinidadian writer and political organiser whose history of the Haitian Revolution shaped Black revolutionary thought.'},
  {id:'edward-wilmot-blyden',name:'Edward Wilmot Blyden',region:'West Africa / diaspora',place:'Liberia / West Africa',active:'19th–early 20th century',role:'intellectual',ideas:['African nationalism','cultural self-respect','Pan-Africanism'],summary:'Earlier intellectual whose writings strongly influenced later Pan-African and African nationalist thought.'},
  {id:'jomo-kenyatta',name:'Jomo Kenyatta',region:'East Africa',place:'Kenya',active:'1920s–1960s',role:'nationalist leader',ideas:['self-government','African nationalism'],summary:'Kenyan nationalist who became a leading independence figure and later Kenya’s first prime minister.'},
  {id:'nnamdi-azikiwe',name:'Nnamdi Azikiwe',region:'West Africa',place:'Nigeria',active:'1930s–1960s',role:'political leader and writer',ideas:['African nationalism','self-government','Pan-Africanism'],summary:'Nigerian nationalist, journalist and later first president of independent Nigeria.'},
  {id:'herbert-macaulay',name:'Herbert Macaulay',region:'West Africa',place:'Nigeria',active:'1890s–1940s',role:'nationalist organiser',ideas:['self-government','anti-colonial politics'],summary:'Pioneer of Nigerian nationalist politics and co-founder of the Nigerian National Democratic Party.'},
  {id:'it-wallace-johnson',name:'I. T. A. Wallace-Johnson',region:'West Africa',place:'Sierra Leone / Gold Coast',active:'1930s–1950s',role:'labour and nationalist organiser',ideas:['anti-colonialism','workers rights','African unity'],summary:'Sierra Leonean activist and journalist who organised workers and promoted West African anti-colonial politics.'},
  {id:'casely-hayford',name:'J. E. Casely Hayford',region:'West Africa',place:'Gold Coast',active:'early 20th century',role:'lawyer and nationalist',ideas:['African nationalism','self-government'],summary:'Gold Coast lawyer and nationalist thinker who argued for African political advancement and self-government.'},
  {id:'sylvanus-olympio',name:'Sylvanus Olympio',region:'West Africa',place:'Togo',active:'1940s–1960s',role:'nationalist leader',ideas:['independence','economic autonomy'],summary:'Togolese nationalist who became the country’s first president at independence.'},
  {id:'kwame-nkrumah',name:'Kwame Nkrumah',region:'West Africa',place:'Ghana',active:'1940s–1960s',role:'revolutionary statesman',ideas:['Pan-Africanism','independence','African unity'],summary:'Ghanaian independence leader who made Pan-African political unity a central project of his government.'},
  {id:'hannah-kudjoe',name:'Hannah Kudjoe',region:'West Africa',place:'Gold Coast / Ghana',active:'1940s–1950s',role:'organiser',ideas:['independence','women’s organising','Pan-Africanism'],summary:'Prominent Ghanaian organiser associated with nationalist mobilisation and women’s participation in the independence movement.'},
  {id:'sarah-bouhaddou',name:'Sarah Bouhaddou',region:'North Africa',place:'Algeria',active:'1950s',role:'resistance activist',ideas:['independence','anti-colonialism'],summary:'Placeholder record for expansion of women’s participation in the Algerian anti-colonial struggle; requires dedicated sourcing before publication.'},
  {id:'modibo-keita',name:'Modibo Keïta',region:'West Africa',place:'Mali',active:'1940s–1960s',role:'political leader',ideas:['independence','African socialism','federalism'],summary:'Malian nationalist and first president of independent Mali, associated with African unity and socialist development.'},
  {id:'aoua-keita',name:'Aoua Keïta',region:'West Africa',place:'Mali',active:'1940s–1960s',role:'trade unionist and political organiser',ideas:['women’s rights','independence','social justice'],summary:'Malian trade unionist and activist who played a major role in political organising and women’s mobilisation.'},
  {id:'ahmed-sekou-toure',name:'Ahmed Sékou Touré',region:'West Africa',place:'Guinea',active:'1940s–1960s',role:'nationalist leader',ideas:['independence','African unity','anti-colonialism'],summary:'Guinean nationalist who led Guinea to independence from France in 1958.'},
  {id:'ruben-um-nyobe',name:'Ruben Um Nyobè',region:'Central Africa',place:'Cameroon',active:'1940s–1958',role:'anti-colonial leader',ideas:['independence','self-determination','UPC'],summary:'Leader of the Union of the Peoples of Cameroon and a central figure in the struggle against French colonial rule.'},
  {id:'felix-moumie',name:'Félix-Roland Moumié',region:'Central Africa',place:'Cameroon',active:'1950s–1960',role:'revolutionary organiser',ideas:['independence','Pan-Africanism'],summary:'Cameroonian anti-colonial leader and UPC figure who continued the struggle after the repression of the movement.'},
  {id:'abel-kingue',name:'Abel Kingué',region:'Central Africa',place:'Cameroon',active:'1940s–1960s',role:'anti-colonial organiser',ideas:['independence','UPC'],summary:'Senior UPC organiser and member of the exiled nationalist leadership.'},
  {id:'frantz-fanon',name:'Frantz Fanon',region:'Caribbean / North Africa',place:'Martinique / Algeria',active:'1940s–1961',role:'revolutionary intellectual',ideas:['decolonisation','national consciousness','psychological liberation'],summary:'Martinican-born psychiatrist and Algerian liberation activist whose work became foundational to decolonisation thought.'}
 ],
 movements:[
  {id:'pan-african-congress-tradition',name:'Pan-African Congress Tradition',period:'1900–1960',region:'Africa & Diaspora',type:'Pan-African',summary:'Series of congresses and networks that developed political ideas of self-determination, anti-colonialism and African unity.'},
  {id:'unia',name:'Universal Negro Improvement Association',period:'1914–1930s',region:'Caribbean / Africa / Diaspora',type:'Pan-African',summary:'Mass Black international organisation founded by Marcus Garvey and Amy Ashwood Garvey.'},
  {id:'west-african-nationalism',name:'West African Nationalism',period:'1910s–1960',region:'West Africa',type:'Independence',summary:'Political and labour movements demanding representation, self-government and eventual independence from colonial rule.'},
  {id:'upc-cameroon',name:'Union of the Peoples of Cameroon',period:'1948–1960s',region:'Central Africa',type:'Anti-colonial',summary:'Nationalist movement that pursued reunification and independence and faced severe colonial repression.'},
  {id:'guinean-independence',name:'Guinean Independence Movement',period:'1940s–1958',region:'West Africa',type:'Independence',summary:'Nationalist and trade union mobilisation culminating in Guinea’s rejection of the French Community proposal and independence in 1958.'},
  {id:'ghana-independence-movement',name:'Gold Coast / Ghana Independence Movement',period:'1940s–1957',region:'West Africa',type:'Independence',summary:'Mass nationalist and labour mobilisation that culminated in Ghanaian independence.'}
 ],
 events:[
  {id:'pan-african-1900',year:'1900',title:'First Pan-African Conference',place:'London',movement:'pan-african-congress-tradition',people:['w-e-b-du-bois'],summary:'Early international gathering addressing colonialism, racism and the political future of people of African descent.'},
  {id:'garvey-unia',year:'1914',title:'UNIA founded',place:'Jamaica',movement:'unia',people:['marcus-garvey','amy-ashwood-garvey'],summary:'Marcus Garvey and Amy Ashwood Garvey establish the Universal Negro Improvement Association.'},
  {id:'pan-african-1919',year:'1919',title:'First Pan-African Congress',place:'Paris',movement:'pan-african-congress-tradition',people:['w-e-b-du-bois'],summary:'Pan-African congress addresses colonial rule, racial equality and self-determination after the First World War.'},
  {id:'pan-african-1921',year:'1921',title:'Second Pan-African Congress',place:'London / Brussels / Paris',movement:'pan-african-congress-tradition',people:['w-e-b-du-bois'],summary:'Congress expands the political programme around colonial reform, racial justice and African self-determination.'},
  {id:'pan-african-1927',year:'1927',title:'Fourth Pan-African Congress',place:'New York',movement:'pan-african-congress-tradition',people:['w-e-b-du-bois'],summary:'Major interwar Pan-African gathering in the United States.'},
  {id:'fifth-pac-1945',year:'1945',title:'Fifth Pan-African Congress',place:'Manchester, United Kingdom',movement:'pan-african-congress-tradition',people:['w-e-b-du-bois','george-padmore','kwame-nkrumah','jomo-kenyatta'],summary:'Pivotal anti-colonial congress that helped connect Black internationalism to the coming African independence generation.'},
  {id:'nkrumah-cpp',year:'1949',title:'Convention People’s Party founded',place:'Gold Coast',movement:'ghana-independence-movement',people:['kwame-nkrumah','hannah-kudjoe'],summary:'Nkrumah’s party builds mass political mobilisation for self-government.'},
  {id:'upc-founded',year:'1948',title:'UPC founded',place:'Cameroon',movement:'upc-cameroon',people:['ruben-um-nyobe'],summary:'Union des Populations du Cameroun is founded and campaigns for reunification and independence.'},
  {id:'ghana-independence-1957',year:'1957',title:'Ghana independence',place:'Accra, Ghana',movement:'ghana-independence-movement',people:['kwame-nkrumah'],summary:'Ghana becomes independent, providing a major symbolic and political centre for Pan-Africanism.'},
  {id:'guinea-independence-1958',year:'1958',title:'Guinea chooses independence',place:'Conakry, Guinea',movement:'guinean-independence',people:['ahmed-sekou-toure'],summary:'Guinea rejects participation in the French Community referendum and becomes independent.'},
  {id:'cameroon-upc-repression',year:'1955–1960s',title:'Repression of the UPC',place:'Cameroon',movement:'upc-cameroon',people:['ruben-um-nyobe','felix-moumie','abel-kingue'],summary:'Colonial and post-colonial security campaigns target the UPC leadership and armed resistance.'},
  {id:'nigeria-independence',year:'1960',title:'Nigeria independence',place:'Nigeria',movement:'west-african-nationalism',people:['nnamdi-azikiwe'],summary:'Nigeria achieves independence as West African nationalist politics enters a new phase.'}
 ],
 sources:[
  {id:'national-archives-garvey',title:'African American Research: Individual Biographies',publisher:'U.S. National Archives',kind:'archive',url:'https://www.archives.gov/research/african-americans/individuals',supports:['marcus-garvey','w-e-b-du-bois']},
  {id:'ascleiden-independence',title:'African Leaders and Independence',publisher:'African Studies Centre Leiden',kind:'research-guide',url:'https://www.ascleiden.nl/content/webdossiers/african-leaders-independence',supports:['kwame-nkrumah','jomo-kenyatta','nnamdi-azikiwe','independence']},
  {id:'unesco-history-africa',title:'General History of Africa',publisher:'UNESCO',kind:'reference',url:'https://www.unesco.org/en/general-history-africa',supports:['anti-colonial resistance','Pan-Africanism','African independence']},
  {id:'fifth-pac-reference',title:'The Fifth Pan-African Congress',publisher:'Manchester archives / scholarly collections',kind:'research',supports:['fifth-pac-1945','george-padmore','kwame-nkrumah']}
 ]
};
